# site settings
title: Portfolio
subtitle: by Tmforshaw
email: tmforshaw@outlook.com
description: My software development portfolio, built using Jekyll.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://tmforshaw.github.io"
author: Tmforshaw
street_address: 1234 Somewhere Road
city: Newcastle Upon Tyne
post_code: NE5
country: United Kingdom
phone: (012) 345-6789

# homepage tiles
tiles-source: projects # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/tmforshaw
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/tmforshaw
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown
# highlighter: rouge
# permalink: /:title/
# paginate: 6

sass:
  style: compressed


# Navigation (header menu)
navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects
  - title: "About"
    url: /about
  - title: "Contact"
    url: /contact

# Collections (optional for projects)
collections:
  projects:
    output: true
    permalink: /projects/:name/

exclude:
  - vendor/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - .gitignore
  - .github/