# Site settings
title: Programming Projects
subtitle: by Tmforshaw
email: tmforshaw@outlook.com
description: A portfolio of my programming projects, built using Jekyll with the Forty theme.
baseurl: ""
url: "https://tmforshaw.github.io"
author: Tmforshaw
street_address: 1234 Somewhere Road
city: Newcastle Upon Tyne
post_code: NE5
country: United Kingdom
phone:
formspree: f/xqaldaqo

# Homepage tiles
tiles-source: projects
tiles-count: 6

# Social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/tmforshaw
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/tmforshaw
  Twitter:
  Facebook:
  Slack:

# Build settings
markdown: kramdown
sass:
  style: compressed

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

exclude:
  - vendor/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - .gitignore
  - .github/